services:
  central_comm:
    build:
      context: ./central_comm
      dockerfile: Dockerfile
    image: bodyjetson/central_comm:latest
    container_name: central_comm
    network_mode: host
    restart: unless-stopped
    environment:
      - ROS_DOMAIN_ID=0
    volumes:
      # Mount shared volume:
      - ./central_comm/ros2_ws/src:/home/ros/ros2_ws/src:rw
      - central_comm_build:/home/ros/ros2_ws/build:rw
      - central_comm_install:/home/ros/ros2_ws/install:rw
      - central_comm_log:/home/ros/ros2_ws/log:rw
    # devices:
      #- /dev/ttyACM0:/dev/ttyACM0        # Pico 
      #- /dev/ttyUSB0:/dev/ttyUSB0        
      #- /dev/ttyUSB1:/dev/ttyUSB1        
      - /dev/i2c-7:/dev/i2c-7            # I²C


volumes:
  central_comm_build: {}
  central_comm_install: {}
  central_comm_log: {}
