services:
  central_comm:
    user: root
    build:
      context: ./central_comm
      dockerfile: Dockerfile
    image: bodyjetson/central_comm:latest
    container_name: central_comm
    network_mode: host
    restart: unless-stopped
    environment:
      - ROS_DOMAIN_ID=0
      - ROS_LOG_DIR=/home/ros/.ros/log
    volumes:
      # Mount shared volume:
      - ./central_comm/ros2_ws/src:/home/ros/ros2_ws/src:rw
      - ./central_comm/ros2_ws/build:/home/ros/ros2_ws/build:rw
      - ./central_comm/ros2_ws/install:/home/ros/ros2_ws/install:rw
      - ./central_comm/ros2_ws/log:/home/ros/.ros/log:rw
    devices:
      #- platform-3610000.usb-usb-0:2.1:1.0        # Pico 
      - type: c
        path: "/dev/serial/by-path/platform-3610000.usb-usb-0:2.2:1.0-port0"
        cgroup_permissions: "rwm"
      - type: c
        path: "/dev/serial/by-path/platform-3610000.usb-usb-0:2.4:1.0-port0"
        cgroup_permissions: "rwm"
      - /dev/i2c-7:/dev/i2c-7            # I²C
