services:
  central_comm:
    user: root
    build:
      context: ./central_comm
      dockerfile: Dockerfile
    image: bodyjetson/central_comm:latest
    container_name: central_comm
    network_mode: host
    restart: unless-stopped
    environment:
      - ROS_DOMAIN_ID=0
      - LANG=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
    volumes:
      # Mount shared volume:
      - ./central_comm/ros2_ws/src:/home/ros/ros2_ws/src:rw
      - ./central_comm/ros2_ws/build:/home/ros/ros2_ws/build:rw
      - ./central_comm/ros2_ws/install:/home/ros/ros2_ws/install:rw
      - ./central_comm/ros2_ws/log:/home/ros/.ros/log:rw
    devices:
      #- /dev/ttyACM0:/dev/ttyACM0        # Pico 
      #- /dev/ttyUSB0:/dev/ttyUSB0        
      #- /dev/ttyUSB1:/dev/ttyUSB1        
      - /dev/i2c-1:/dev/i2c-1            # I²C


volumes:
  central_build: {}
  central_install: {}
  central_log: {}