services:
  central_comm:
    user: root
    build:
      context: ./central_comm
      dockerfile: Dockerfile
    image: bodyjetson/central_comm:latest
    container_name: central_comm
    network_mode: host
    restart: unless-stopped
    environment:
      - ROS_DOMAIN_ID=0
      - ROS_LOCALHOST_ONLY=0
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONEDDS_URI=file:///etc/cyclonedds/cyclonedds.xml
      - ROS_LOG_DIR=/home/ros/.ros/log
    volumes:
      # Mount shared volume:
      - ./central_comm/ros2_ws/src:/home/ros/ros2_ws/src:rw
      - ./central_comm/ros2_ws/build:/home/ros/ros2_ws/build:rw
      - ./central_comm/ros2_ws/install:/home/ros/ros2_ws/install:rw
      - ./central_comm/ros2_ws/log:/home/ros/.ros/log:rw
      - ./ros_network/cyclonedds.xml:/etc/cyclonedds/cyclonedds.xml:ro
    devices:
      - /dev/ttyACM0:/dev/ttyACM0        # Pico 
      #- /dev/ttyUSB0:/dev/ttyUSB0        
      #- /dev/ttyUSB1:/dev/ttyUSB1        
      - /dev/i2c-7:/dev/i2c-7            # I²C

  web_ui:
    user: root
    build:
      context: ./web_ui
      dockerfile: Dockerfile
    image: bodyjetson/web_ui:latest
    container_name: web_ui
    network_mode: host
    restart: unless-stopped
    environment:
      - ROS_DOMAIN_ID=0
      - ROS_LOCALHOST_ONLY=0
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONEDDS_URI=file:///etc/cyclonedds/cyclonedds.xml
      - UI_BRIDGE_HOST=0.0.0.0
      - UI_BRIDGE_PORT=8000
      - ROS_LOG_DIR=/home/ros/.ros/log
    volumes:
      - ./ros_network/cyclonedds.xml:/etc/cyclonedds/cyclonedds.xml:ro
      # Web UI workspace
      - ./web_ui/ros2_ws/src:/home/ros/ros2_ws/src:rw
      - ./web_ui/ros2_ws/build:/home/ros/ros2_ws/build:rw
      - ./web_ui/ros2_ws/install:/home/ros/ros2_ws/install:rw
      - ./web_ui/ros2_ws/log:/home/ros/.ros/log:rw
      - ./web_ui/frontend:/home/ros/frontend:ro

      # Reuse custom message packages from central_comm (single source of truth)
      - ./central_comm/ros2_ws/src/serial_msg:/home/ros/ros2_ws/src/serial_msg:ro
      - ./central_comm/ros2_ws/src/tcp_msg:/home/ros/ros2_ws/src/tcp_msg:ro
      - ./action_layer/ros2_ws/src/behavior_msgs:/home/ros/ros2_ws/src/behavior_msgs:ro

  visual_perception:
    user: root
    build:
      context: ./visual_perception
      dockerfile: Dockerfile
    image: bodyjetson/visual_perception:latest
    container_name: visual_perception
    network_mode: host
    restart: unless-stopped
    runtime: nvidia
    environment:
      - ROS_DOMAIN_ID=0
      - ROS_LOCALHOST_ONLY=0
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONEDDS_URI=file:///etc/cyclonedds/cyclonedds.xml
      - ROS_LOG_DIR=/home/ros/.ros/log
      - AUTO_BUILD_ENGINE=1
    volumes:
      - ./ros_network/cyclonedds.xml:/etc/cyclonedds/cyclonedds.xml:ro

      # Workspace
      - ./visual_perception/ros2_ws/src:/home/ros/ros2_ws/src:rw
      - ./visual_perception/ros2_ws/build:/home/ros/ros2_ws/build:rw
      - ./visual_perception/ros2_ws/install:/home/ros/ros2_ws/install:rw
      - ./visual_perception/ros2_ws/log:/home/ros/.ros/log:rw
      - ./visual_perception/models:/home/ros/models:rw

      # Configs / helper files
      - ./visual_perception/config:/home/ros/config:rw

      # Reuse custom message packages from central_comm (single source of truth)
      - ./central_comm/ros2_ws/src/serial_msg:/home/ros/ros2_ws/src/serial_msg:ro

  camera_relay:
    user: root
    build:
      context: ./camera_relay
      dockerfile: Dockerfile
    image: bodyjetson/camera_relay:latest
    container_name: camera_relay
    network_mode: host
    restart: unless-stopped
    runtime: nvidia
    environment:
      - ROS_DOMAIN_ID=0
      - ROS_LOCALHOST_ONLY=0
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONEDDS_URI=file:///etc/cyclonedds/cyclonedds.xml
      - ROS_LOG_DIR=/home/ros/.ros/log
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all

      # Launch parameters for camera_relay.launch.py
      - INPUT_COMPRESSED_TOPIC=/camera/image_raw/compressed
      - INPUT_CAMERA_INFO_TOPIC=/camera/camera_info
      - OUTPUT_COMPRESSED_TOPIC=/relay/camera/image_raw/compressed
      - OUTPUT_RAW_TOPIC=/relay/camera/image_raw
      - OUTPUT_CAMERA_INFO_TOPIC=/relay/camera/camera_info

    volumes:
      - ./ros_network/cyclonedds.xml:/etc/cyclonedds/cyclonedds.xml:ro

      # Workspace
      - ./camera_relay/ros2_ws/src:/home/ros/ros2_ws/src:rw
      - ./camera_relay/ros2_ws/build:/home/ros/ros2_ws/build:rw
      - ./camera_relay/ros2_ws/install:/home/ros/ros2_ws/install:rw
      - ./camera_relay/ros2_ws/log:/home/ros/.ros/log:rw

  action_layer:
    user: root
    build:
      context: ./action_layer
      dockerfile: Dockerfile
    image: bodyjetson/action_layer:latest
    container_name: action_layer
    network_mode: host
    restart: unless-stopped
    environment:
      - ROS_DOMAIN_ID=0
      - ROS_LOCALHOST_ONLY=0
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONEDDS_URI=file:///etc/cyclonedds/cyclonedds.xml
      - ROS_LOG_DIR=/home/ros/.ros/log
    volumes:
      - ./ros_network/cyclonedds.xml:/etc/cyclonedds/cyclonedds.xml:ro

      # Workspace
      - ./action_layer/ros2_ws/src:/home/ros/ros2_ws/src:rw
      - ./action_layer/ros2_ws/build:/home/ros/ros2_ws/build:rw
      - ./action_layer/ros2_ws/install:/home/ros/ros2_ws/install:rw
      - ./action_layer/ros2_ws/log:/home/ros/.ros/log:rw

      # Reuse custom message packages from central_comm (single source of truth)
      - ./central_comm/ros2_ws/src/serial_msg:/home/ros/ros2_ws/src/serial_msg:ro