SERVICE := "central_comm"
COMPOSE := "docker compose"
# Paths/vars
ROS_SETUP := "/home/ros/ros2_ws/install/setup.bash"

# Build all Docker service images
build:
    {{COMPOSE}} build

# Build base image
build-base:
	docker build -t bodyjetson-ros:humble base

# Build service image
build-service:
	docker build -t bodyjetson/{{SERVICE}}:latest {{SERVICE}}

# Start all containers
up:
    {{COMPOSE}} up -d

# Stop all containers
down:
    {{COMPOSE}} down

# Tail logs of the service
logs:
    {{COMPOSE}} logs -f {{SERVICE}}

# Exec a shell inside the service container
sh:
    docker exec -it {{SERVICE}} bash

# Clean local ROS2 build artifacts
clean:
    sudo rm -rf central_comm/ros2_ws/build \
        central_comm/ros2_ws/install \
        central_comm/ros2_ws/log
    
    sudo rm -rf action_layer/ros2_ws/build \
        action_layer/ros2_ws/install \
        action_layer/ros2_ws/log
    
    sudo rm -rf camera_relay/ros2_ws/build \
        camera_relay/ros2_ws/install \
        camera_relay/ros2_ws/log
    
    sudo rm -rf visual_perception/ros2_ws/build \
        visual_perception/ros2_ws/install \
        visual_perception/ros2_ws/log
    
    sudo rm -rf web_ui/ros2_ws/build \
        web_ui/ros2_ws/install \
        web_ui/ros2_ws/log

# Rebuild all images and restart all services
rebuild: down clean
    {{COMPOSE}} up -d --build

# Full Docker image rebuild without layer cache
rebuild-full: down clean
    {{COMPOSE}} build --no-cache
    {{COMPOSE}} up -d

# Run Test.py inside the container
test:
    @docker compose exec -it {{SERVICE}} bash -lc "source //home/ros/ros2_ws/install/setup.bash && python3 /home/ros/ros2_ws/src/xiao_bridge/xiao_bridge/Test.py"

console-out:
    tail -f central_comm/ros2_ws/log/*.log

topic-list:
    @docker exec -it {{SERVICE}} bash -lc ' \
    source {{ROS_SETUP}} && \
    ros2 topic list \
    '

node-list:
    @docker exec -it {{SERVICE}} bash -lc ' \
    source {{ROS_SETUP}} && \
    ros2 node list \
    '