default:
    @just --list

compiledb:
    pio run --target compiledb

build-debug:
    pio run -e debug

build-release:
    pio run -e release

upload-debug:
    pio run -e debug --target upload

upload-release:
    pio run -e release --target upload

clean:
    pio run --target clean

monitor:
    pio device monitor

lib-search QUERY:
    pio lib search "{{QUERY}}"

lib-install LIB:
    pio lib install "{{LIB}}"
    just compiledb

devices:
    pio device list
