; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter, extra scripting
;   Upload options: custom port, speed and extra flags
;   Library options: dependencies, extra library storages
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
;
; https://arduino-pico.readthedocs.io/en/latest/platformio.html#

; old config
; [env:pico]
; platform = https://github.com/maxgerhardt/platform-raspberrypi.git
; board = pico
; framework = arduino
; board_build.core = earlephilhower
; extra_scripts = pre:build.py
; lib_deps =
;    khoih-prog/RP2040_PWM@^1.7.0

[platformio]
default_envs = release

[common]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower
extra_scripts = pre:build.py

[env:debug]
extends = common
build_type = debug
build_flags =
    -DDEBUG=1
    -DCORE_DEBUG_LEVEL=5
    -O0
    -g3

[env:release]
extends = common
build_type = release
build_flags =
    -DNDEBUG
    -DCORE_DEBUG_LEVEL=1
    -O2
    -g0
