build packages="":
    #!/usr/bin/env bash
    cd ros2_ws
    if [ -n "{{ packages }}" ]; then
        colcon build --symlink-install --packages-select {{ packages }}
    else
        colcon build --symlink-install
    fi

run package node *args:
    #!/usr/bin/env bash
    cd ./ros2_ws
    source ./install/setup.bash
    ros2 run {{ package }} {{ node }} {{ args }}

run-bridge *args:
    just run ui_bridge_cpp ui_bridge_cpp_node --ros-args -p doc_root:=$(pwd)/frontend {{ args }}

launch-bridge *args:
    #!/usr/bin/env bash
    cd ./ros2_ws
    source ./install/setup.bash
    ros2 launch ui_bridge_cpp ui_bridge_cpp.launch.py doc_root:=$(cd .. && pwd)/frontend {{ args }}

deps:
    rosdep install -i --from-path src --rosdistro $ROS_DISTRO -y

source-overlay:
    #!/usr/bin/env bash
    source "./install/setup.$(basename "$SHELL" | grep -E '^(bash|zsh)$' || echo sh)"

source-underlay:
    #!/usr/bin/env bash
    source "/opt/ros/humble/setup.$(basename "$SHELL" | grep -E '^(bash|zsh)$' || echo sh)"

rosdep-update:
    rosdep update --rosdistro $ROS_DISTRO

format:
    find ./src/ -name "*.cpp" -o -name "*.h" | xargs clang-format -i

lint:
    clang-tidy src/*/*.cpp src/*/*.h -p .

default:
    @just --list
